import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { lessons, levels } from '../../../src/data';
import { campaignNarrative } from '../../../src/data/campaign/narrative';
import { sceneBefore } from '../../../src/data/campaign/cutscenes';
import { ROBOT_UNLOCK_LEVELS } from '../../../src/domain/robots';
import { indentSource } from '../../../src/domain/scope';
import type { RobotRole } from '../../../src/domain/types';
import { CHALLENGE_WORDS } from '../../../src/features/workspace/challenges';

/**
 * docs/campaign/shifts/ holds one page per shift, rendered from the campaign data so it can't drift from the
 * game. `npm run docs:gen` rewrites the pages; this test fails when they are stale.
 */
const outDir = join(process.cwd(), 'docs/campaign/shifts');

const robotNames: Record<RobotRole, string> = {
  query: 'Query (counter)',
  prep: 'Brew (kitchen)',
  floor: 'Porter (floor)',
};
const actNames = ['Prologue', 'Act I: Query', 'Act II: Brew', 'Act III: Porter', 'Act IV: the whole crew'];

function actFor(index: number): number {
  const act = levels[index]!.act;
  if (act !== undefined) return act;
  return index === 0 ? 0 : 1;
}

const fence = (source: string) => '```text\n' + indentSource(source.trim()) + '\n```';

function renderShift(index: number): string {
  const level = levels[index]!,
    lesson = lessons[index]!,
    story = campaignNarrative[index]!,
    shift = index + 1,
    scene = sceneBefore(index);
  const out: string[] = [];
  out.push(`# ${level.id}: ${story.title}`, '');
  out.push(
    `${actNames[actFor(index)]} · ${level.active_tables} table${level.active_tables === 1 ? '' : 's'} · ` +
      `${level.seeds.length} seed${level.seeds.length === 1 ? '' : 's'}`,
    '',
  );
  if (scene) out.push(`The cutscene _${scene.title}_ plays before this shift: ${scene.logline}`, '');
  out.push(story.story, '', `**Goal.** ${story.objective}`, '', `**Lesson.** ${lesson.note}`, '');
  if (level.programming_enabled)
    out.push(
      `**Stars.** One for serving every seed, two for ${level.block_target} blocks or fewer, three for also ` +
        `finishing in ${level.instruction_target} executed steps or fewer. The reference uses ` +
        `${level.reference_block_count} blocks.` +
        // Past the usual two blocks of room, the target is set by a longer way in (tests/unit/data/ways-in.test.ts).
        (level.block_target > level.reference_block_count + 2
          ? ' The target leaves room for the longer ways in listed in the [audit](../AUDIT.md), such as robots that keep batching.'
          : ''),
      '',
    );
  // Optional, and shown in the game once the shift has been served: tests/unit/data/challenges.test.ts sets them.
  if (level.challenges) {
    out.push('**Challenges.** Optional, for no stars, and shown once the shift has been served.', '');
    for (const { measure, target } of level.challenges) {
      const words = CHALLENGE_WORDS.en[measure];
      out.push(`- _${words.name}._ ${words.goal(target)} ${words.note}`);
    }
    out.push('');
  }
  out.push('## Customers in the first seed', '');
  for (const customer of level.seeds[0]!.customers) {
    const said = customer.phrase ? `“${customer.phrase}”` : '(nothing)';
    out.push(`- ${said}${customer.clarification ? `, then “${customer.clarification}”` : ''}`);
  }
  out.push('');

  const robots = (['query', 'prep', 'floor'] as const).filter((role) => shift >= ROBOT_UNLOCK_LEVELS[role]);
  const solution = 'robotSolution' in lesson ? lesson.robotSolution : undefined;
  out.push('## Reference programs', '');
  if (!level.programming_enabled)
    out.push('Nothing to program: this shift runs an automatic service to watch.', '', fence(lesson.solution), '');
  else {
    out.push(
      'Written in the text-editor language. Moka runs the kitchen and Pip the floor until a robot takes the role over.',
      '',
    );
    for (const role of robots) {
      out.push(`### ${robotNames[role]}`, '', fence(role === 'query' ? lesson.solution : (solution?.[role] ?? '')), '');
    }
  }
  return out.join('\n');
}

function renderIndex(): string {
  const rows = levels.map((level, index) => `- [${level.id}: ${campaignNarrative[index]!.title}](${level.id}.md)`);
  return [
    '# Shift pages',
    '',
    'Generated by `npm run docs:gen` from `src/data/`. Do not edit by hand.',
    '',
    ...rows,
    '',
  ].join('\n');
}

function renderAll(): Map<string, string> {
  const pages = new Map<string, string>([['README.md', renderIndex()]]);
  levels.forEach((level, index) => pages.set(`${level.id}.md`, renderShift(index)));
  return pages;
}

describe('shift pages in docs/campaign/shifts', () => {
  const pages = renderAll();

  if (process.env.UPDATE_SHIFT_DOCS) {
    it('rewrites the pages', () => {
      rmSync(outDir, { recursive: true, force: true });
      mkdirSync(outDir, { recursive: true });
      for (const [name, text] of pages) writeFileSync(join(outDir, name), text);
      expect(readdirSync(outDir)).toHaveLength(pages.size);
    });
    return;
  }

  it('has one page per shift and nothing else', () => {
    expect(existsSync(outDir)).toBe(true);
    expect(readdirSync(outDir).sort()).toEqual([...pages.keys()].sort());
  });

  it.each([...pages.keys()])('%s is up to date (run npm run docs:gen)', (name) => {
    expect(readFileSync(join(outDir, name), 'utf8')).toBe(pages.get(name));
  });
});
