import { test,expect } from '@playwright/test';
import type { Page } from '@playwright/test';
import { lessons,stories } from '../../src/data';
import { newSave,SAVE_KEY } from '../../src/features/campaign/save/persistence';
async function ready(page:Page){await page.goto('/');await expect(page.getByRole('heading',{name:'Good coffee. Better instructions.'})).toBeVisible();}
async function finishObservation(page:Page){await page.getByRole('button',{name:'Watch service'}).click();await expect(page.getByRole('button',{name:'Back to campaign',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'4× playback',exact:true}).click();await page.clock.fastForward(40_000);await expect(page.getByRole('button',{name:'Back to campaign',exact:true})).toBeVisible();await page.getByRole('button',{name:'Back to campaign',exact:true}).click();}
async function fit(page:Page,selector:string){const box=await page.locator(selector).boundingBox();expect(box).not.toBeNull();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.y).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(page.viewportSize()!.width+1);expect(box!.y+box!.height).toBeLessThanOrEqual(page.viewportSize()!.height+1);}
test('a new café through observation, a win, failure, debugging, and persistence',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await ready(page);
 await page.getByRole('button',{name:'Explore the 14 shifts'}).click();await expect(page.locator('.shift-card')).toHaveCount(14);await expect(page.getByRole('button',{name:'Shift 3: Boot Sequence, locked',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Start shift',exact:true}).click();await expect(page.getByRole('button',{name:'Add block',exact:true})).toBeDisabled();await expect(page.getByText('Automatic service',{exact:true})).toBeVisible();await finishObservation(page);
 await page.getByRole('button',{name:'Start shift',exact:true}).click();await finishObservation(page);
 await page.getByRole('button',{name:'Start shift',exact:true}).click();await expect(page.getByRole('heading',{name:'A voice at the counter'})).toBeVisible();await page.getByRole('button',{name:"Let's open the café"}).click();
 for(const command of ['TICKET','ITEM coffee','SUBMIT']){await page.locator('#instruction').selectOption(command);await page.getByRole('button',{name:'Add block',exact:true}).click();}
 await page.keyboard.press('Control+Enter');await expect(page.getByRole('status',{name:'Service status'})).toContainText('Every order checked');await expect(page.getByRole('button',{name:'Stop & edit'})).toBeVisible();await expect(page.getByLabel('Block 1',{exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Inspect',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Step block',exact:true}).click();await expect(page.locator('.trace-current')).toContainText('LISTEN');await page.getByRole('button',{name:'Next customer',exact:true}).click();await expect(page.locator('.inspector-nav')).toContainText('02 / 02');await page.getByRole('button',{name:'Restart seed',exact:true}).click();await expect(page.locator('.inspector-nav')).toContainText('L03_B');await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('button',{name:'Stop & edit'}).click();
 await page.getByRole('button',{name:'Text',exact:true}).click();await page.getByRole('textbox',{name:'Program source'}).fill('BROKEN\nLISTEN');await page.keyboard.press('Control+Enter');await expect(page.getByRole('status',{name:'Service status'})).toContainText('Unknown or locked instruction: BROKEN');await page.getByRole('button',{name:'Results',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Block 1');await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('button',{name:'Stop & edit'}).click();await page.getByRole('button',{name:'Blocks',exact:true}).click();await expect(page.locator('.block.failure')).toHaveAttribute('data-line','0');
 await page.reload();await page.getByRole('button',{name:'Text',exact:true}).click();await expect(page.getByRole('textbox',{name:'Program source'})).toHaveValue('BROKEN\nLISTEN');await page.getByRole('button',{name:'Back to campaign',exact:true}).click();await page.getByRole('button',{name:'Start shift',exact:true}).click();await page.getByRole('button',{name:'Text',exact:true}).click();await expect(page.getByRole('textbox',{name:'Program source'})).toHaveValue(lessons[2].solution);
 expect(errors).toEqual([]);
});
test('all remaining shifts, every interlude, and the final ending',async({page})=>{
 const seed={...newSave(),unlocked:2,selected:2,stars:{0:0,1:0}};
 await page.addInitScript(({key,save})=>localStorage.setItem(key,JSON.stringify(save)),{key:SAVE_KEY,save:seed});await ready(page);await page.getByRole('button',{name:'Continue your café'}).click();
 for(let index=2;index<14;index++){
  if(stories[index]){await expect(page.getByRole('heading',{name:stories[index].title})).toBeVisible();await page.getByRole('button',{name:"Let's open the café"}).click();}
  await page.getByRole('button',{name:'Help',exact:true}).click();await page.getByRole('button',{name:'Reveal worked example'}).click();await page.getByRole('button',{name:'Use this example'}).click();await page.getByRole('button',{name:'Run service'}).click();await expect(page.getByRole('status',{name:'Service status'})).toContainText('★★★');
  if(index<13){await page.getByRole('button',{name:'Back to campaign',exact:true}).click();await page.getByRole('button',{name:'Start shift',exact:true}).click();}else await page.getByRole('button',{name:'Closing time',exact:true}).click();
 }
 await expect(page.getByRole('heading',{name:'Closing time.'})).toBeVisible();await expect(page.locator('.ending-score')).toContainText('36 / 36');await expect(page.getByText('“It is now.”',{exact:true})).toBeVisible();
});
test('settings, lossless source, structural editing, and import/export confirmation',async({page})=>{
 const seed={...newSave(),unlocked:13,selected:7,story:{7:true},drafts:{7:'LISTEN\nTICKET\nITEM heard\nSUBMIT'}};
 await page.addInitScript(({key,save})=>{if(!sessionStorage.getItem('seeded')){localStorage.setItem(key,JSON.stringify(save));sessionStorage.setItem('seeded','1');}},{key:SAVE_KEY,save:seed});await ready(page);await page.getByRole('button',{name:'Open the café',exact:true}).click();
 await page.getByLabel('Block 1',{exact:true}).focus();await page.locator('#instruction').selectOption('IF tea');await page.getByRole('button',{name:'Add block',exact:true}).click();await expect(page.getByLabel('Block 2',{exact:true})).toHaveValue('IF tea');await expect(page.getByLabel('Block 3',{exact:true})).toHaveValue('END');
 await page.getByRole('button',{name:'Drag block 2 and its group',exact:true}).focus();await page.keyboard.press('Space');await expect(page.locator('[id^=DndLiveRegion]')).toContainText('Picked up draggable item');await page.keyboard.press('ArrowUp');await expect(page.locator('[id^=DndLiveRegion]')).toContainText('over droppable area 0');await page.keyboard.press('Space');await expect(page.getByLabel('Block 1',{exact:true})).toHaveValue('IF tea');await expect(page.getByLabel('Block 2',{exact:true})).toHaveValue('END');
 await page.getByRole('button',{name:'Delete block 2',exact:true}).click();await page.getByRole('button',{name:'Delete block 1',exact:true}).click();
 await page.getByRole('button',{name:'Text',exact:true}).click();const text='# my café\n\n LISTEN \nTICKET\nITEM heard\nSUBMIT\n';await page.getByRole('textbox',{name:'Program source'}).fill(text);await page.getByRole('button',{name:'Blocks',exact:true}).click();await page.getByRole('button',{name:'Text',exact:true}).click();await expect(page.getByRole('textbox',{name:'Program source'})).toHaveValue(text);
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('slider',{name:'Music volume',exact:true}).fill('0');await page.getByRole('checkbox',{name:'Reduced motion'}).check();await page.reload();await expect(page.getByRole('slider',{name:'Music volume',exact:true})).toHaveValue('0');await expect(page.getByRole('checkbox',{name:'Reduced motion'})).toBeChecked();
 const exported=page.waitForEvent('download');await page.getByRole('button',{name:'Export café'}).click();const file=await exported;expect(file.suggestedFilename()).toBe('caffeine-protocol-save.json');
 await page.getByRole('button',{name:'Start a new café',exact:true}).click();await page.getByRole('button',{name:'Keep my café'}).click();await expect(page.getByRole('heading',{name:'The little things.'})).toBeVisible();
 await page.getByRole('button',{name:'Start a new café',exact:true}).click();await page.getByRole('button',{name:'Start new café',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();await expect(page.getByRole('slider',{name:'Music volume',exact:true})).toHaveValue('0');
 await page.getByLabel('Import save file').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await expect(page.getByRole('alert')).toBeVisible();
 await page.getByLabel('Import save file').setInputFiles({name:'cafe.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(seed))});await expect(page.getByRole('dialog')).toContainText('Replace this café?');await page.getByRole('button',{name:'Keep current café'}).click();
 await page.getByLabel('Import save file').setInputFiles({name:'cafe.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(seed))});await page.getByRole('button',{name:'Replace café',exact:true}).click();await page.getByRole('button',{name:'Back to campaign',exact:true}).click();await expect(page.getByRole('button',{name:'Shift 14: Employee of the Month',exact:true})).toBeEnabled();
});
for(const width of [1280,1100])test(`framing and working controls at ${width} × 720`,async({page})=>{
 await page.setViewportSize({width,height:720});await page.addInitScript(({key,save})=>localStorage.setItem(key,JSON.stringify(save)),{key:SAVE_KEY,save:{...newSave(),unlocked:13,selected:13,story:{13:true}}});await ready(page);await page.getByRole('button',{name:'Open the café',exact:true}).click();await fit(page,'.editor-panel');await fit(page,'.scene-space');await fit(page,'.run-button');expect(await page.locator('body').evaluate(el=>el.scrollWidth)).toBeLessThanOrEqual(width);await expect(page.locator('canvas')).toBeVisible();await expect(page.locator('.webgl-fallback')).toHaveCount(0);await page.screenshot({path:`test-results/workspace-${width}.png`});
 await page.getByRole('button',{name:'Help',exact:true}).click();await fit(page,'dialog');
});
test('offline reload retains the complete static game',async({page,context})=>{
 await ready(page);await page.evaluate(async()=>{await navigator.serviceWorker.ready;await new Promise<void>(resolve=>{if(navigator.serviceWorker.controller)resolve();else navigator.serviceWorker.addEventListener('controllerchange',()=>resolve(),{once:true});});});
 await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{name:'Good coffee. Better instructions.'})).toBeVisible();await page.getByRole('button',{name:'Open the café',exact:true}).click();await expect(page.getByRole('button',{name:'Watch service'})).toBeVisible();await expect(page.locator('canvas')).toBeVisible();
});
test('without WebGL the editor and validation remain readable and usable',async({page})=>{
 await page.addInitScript(({key,save})=>{localStorage.setItem(key,JSON.stringify(save));const get=HTMLCanvasElement.prototype.getContext;Object.defineProperty(HTMLCanvasElement.prototype,'getContext',{value:function(this:HTMLCanvasElement,type:string,...args:unknown[]){return type.includes('webgl')?null:Reflect.apply(get,this,[type,...args]);}});},{key:SAVE_KEY,save:{...newSave(),unlocked:2,selected:2,story:{2:true},drafts:{2:lessons[2].solution}}});
 await ready(page);await page.getByRole('button',{name:'Open the café',exact:true}).click();await expect(page.locator('.webgl-fallback')).toBeVisible();await page.getByRole('button',{name:'Run service'}).click();await expect(page.getByRole('status',{name:'Service status'})).toContainText('Every order checked');await page.getByRole('button',{name:'Inspect',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Exact simulation timestamps');
});
