import { afterEach,describe,it,expect,vi } from 'vitest';
import { cleanup,render,screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { useState } from 'react';
import { Editor } from '../src/components/Editor';
afterEach(cleanup);
function Harness({initial='LISTEN',locked=false,observation=false}:{initial?:string;locked?:boolean;observation?:boolean}){const [source,setSource]=useState(initial),[text,setText]=useState(false);return <><Editor source={source} onChange={setSource} level={14} locked={locked} observation={observation} textMode={text} onTextMode={setText}/><output aria-label="Current source">{source}</output></>;}
describe('keyboard and mouse editor component behavior',()=>{
 it('adds a block from the library',async()=>{const user=userEvent.setup();render(<Harness/>);await user.click(screen.getByRole('button',{name:'Add block'}));expect(screen.getByLabelText('Current source').textContent).toBe('LISTEN\nTICKET');});
 it('automatically adds END for each structural opener',async()=>{const user=userEvent.setup();render(<Harness/>);for(const c of ['IF tea','EACH','FUNCTION build_ticket']){await user.selectOptions(screen.getByLabelText(/INSTRUCTION LIBRARY/),c);await user.click(screen.getByRole('button',{name:'Add block'}));expect(screen.getByLabelText('Current source').textContent).toContain(c+'\nEND');}});
 it('inserts after the selected source line',async()=>{const user=userEvent.setup();render(<Harness initial={'LISTEN\nSUBMIT'}/>);await user.click(screen.getByLabelText('Block 1',{exact:true}));await user.click(screen.getByRole('button',{name:'Add block'}));expect(screen.getByLabelText('Current source').textContent).toBe('LISTEN\nTICKET\nSUBMIT');});
 it('replaces an instruction',async()=>{const user=userEvent.setup();render(<Harness initial={'LISTEN\nITEM coffee'}/>);await user.selectOptions(screen.getByLabelText('Block 2',{exact:true}),'ITEM tea');expect(screen.getByLabelText('Current source').textContent).toBe('LISTEN\nITEM tea');});
 it('moves and deletes single blocks',async()=>{const user=userEvent.setup();render(<Harness initial={'LISTEN\nTICKET\nSUBMIT'}/>);await user.click(screen.getByRole('button',{name:'Move block 2 down'}));expect(screen.getByLabelText('Current source').textContent).toBe('LISTEN\nSUBMIT\nTICKET');await user.click(screen.getByRole('button',{name:'Delete block 2'}));expect(screen.getByLabelText('Current source').textContent).toBe('LISTEN\nTICKET');});
 it('disables all mutations during playback',async()=>{const user=userEvent.setup();render(<Harness locked/>);for(const name of ['Add block','Move block 1 up','Move block 1 down','Delete block 1'])expect((screen.getByRole('button',{name}) as HTMLButtonElement).disabled).toBe(true);await user.click(screen.getByRole('button',{name:'Text'}));expect((screen.getByRole('textbox',{name:'Program source'}) as HTMLTextAreaElement).readOnly).toBe(true);});
 it('retains comments and whitespace between views',async()=>{const user=userEvent.setup();const text='# hello\n\n LISTEN \n';render(<Harness initial={text}/>);await user.click(screen.getByRole('button',{name:'Text'}));expect((screen.getByRole('textbox',{name:'Program source'}) as HTMLTextAreaElement).value).toBe(text);await user.click(screen.getByRole('button',{name:'Blocks'}));expect(screen.getByLabelText('Current source').textContent).toBe(text);});
 it('highlights the active and failing source lines',()=>{Element.prototype.scrollIntoView=vi.fn();render(<Editor source={'LISTEN\nTICKET'} onChange={()=>{}} level={3} locked activeLine={0} failureLine={1} observation={false} textMode={false} onTextMode={()=>{}}/>);expect(document.querySelector('.block.active')?.getAttribute('data-line')).toBe('0');expect(document.querySelector('.block.failure')?.getAttribute('data-line')).toBe('1');});
 it('observation uses an automatic locked routine',()=>{render(<Harness observation/>);expect(screen.getByText('Automatic service')).toBeTruthy();expect((screen.getByRole('button',{name:'Add block'}) as HTMLButtonElement).disabled).toBe(true);expect(screen.queryByLabelText('Block 1',{exact:true})).toBeNull();});
});
