/** Soundtrack + effect ids generated by tools/audio and shipped in public/audio. */
export const SOUNDS = ['click', 'morning_loop', 'retry', 'serve', 'success'] as const;
export type SoundName = (typeof SOUNDS)[number];
