/** Soundtrack, room tone and effect ids generated by tools/audio and shipped in public/audio. */
export const SOUNDS = ['cafe_loop', 'cafe_room', 'click', 'retry', 'serve', 'success', 'pour'] as const;
export type SoundName = (typeof SOUNDS)[number];
