import { useRef, useState, useEffect } from 'react';
import { DndContext, KeyboardSensor, PointerSensor, useSensor, useSensors, closestCenter } from '@dnd-kit/core';
import { SortableContext, useSortable, verticalListSortingStrategy, sortableKeyboardCoordinates } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { ArrowUp, ArrowDown, X, GripVertical, Plus, LockKeyhole, Code2, Blocks } from 'lucide-react';
import type { RobotRole } from '../domain/types';
import { robotCommands } from '../domain/robotProgram';
import { isOpening } from '../domain/program';
import { deleteBlock,insertBlock,moveBlock,moveGroup } from '../domain/editor';
import { labels } from '../data';
function category(command:string){return command.startsWith('IF ')||['LISTEN','END','ELSE','EACH','REPEAT'].includes(command)||command.startsWith('JUMP')||command.startsWith('POSITION')?'flow':command.includes('build_ticket')||command==='RETURN'?'function':command==='HELP'||command==='ERROR'?'help':'action';}
function Row({id,command,depth,selected,locked,active,failure,options,onSelect,onReplace,onMove,onDelete}:{id:number;command:string;depth:number;selected:boolean;locked:boolean;active:boolean;failure:boolean;options:string[];onSelect:()=>void;onReplace:(c:string)=>void;onMove:(d:number)=>void;onDelete:()=>void}){
  const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:String(id),disabled:locked});const rowRef=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{if(active)rowRef.current?.scrollIntoView({block:'nearest',behavior:'instant'});},[active]);
  return <div ref={node=>{setNodeRef(node);rowRef.current=node;}} className={`block ${category(command)} ${selected?'selected':''} ${active?'active':''} ${failure?'failure':''}`} style={{marginLeft:depth*12,transform:CSS.Transform.toString(transform),transition,opacity:isDragging?.4:1}} onClick={onSelect} data-line={id}>
    <button className="grip" aria-label={`Drag block ${id+1} and its group`} disabled={locked} {...attributes} {...listeners}><GripVertical size={13}/><span>{String(id+1).padStart(2,'0')}</span></button>
    {command.startsWith('MOVE ')?<><select aria-label={`Block ${id+1} direction`} value={command.split(' ')[1]} disabled={locked} onChange={e=>onReplace(`MOVE ${e.target.value} ${command.split(' ')[2]}`)}>{['UP','DOWN','LEFT','RIGHT'].map(d=><option key={d}>{d}</option>)}</select><input className="tile-count" type="number" min={1} max={19} step={1} aria-label={`Block ${id+1} tiles`} value={command.split(' ')[2]} disabled={locked} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=19)onReplace(`MOVE ${command.split(' ')[1]} ${n}`);}}/><span>tiles</span></>:(<select value={command} onFocus={onSelect} onChange={e=>onReplace(e.target.value)} aria-label={`Block ${id+1}`} disabled={locked} title={labels[command]??command}>{!options.includes(command)&&<option value={command}>{command}</option>}{options.map(c=><option value={c} key={c}>{labels[c]??c}</option>)}</select>)}

    <div className="block-actions"><button aria-label={`Move block ${id+1} up`} disabled={locked||id===0} onClick={()=>onMove(-1)}><ArrowUp size={12}/></button><button aria-label={`Move block ${id+1} down`} disabled={locked} onClick={()=>onMove(1)}><ArrowDown size={12}/></button><button aria-label={`Delete block ${id+1}`} disabled={locked} onClick={onDelete}><X size={13}/></button></div>
  </div>;
}
export function Editor({role="query",source,onChange,level,locked,observation,activeLine=-1,failureLine=-1,textMode,onTextMode}:{role?:RobotRole;source:string;onChange:(v:string)=>void;level:number;locked:boolean;observation:boolean;activeLine?:number;failureLine?:number;textMode:boolean;onTextMode:(v:boolean)=>void}){
  const [selected,setSelected]=useState(-1),[command,setCommand]=useState('TICKET');const options=robotCommands(role,level);
  useEffect(()=>{setCommand(role==='query'?'TICKET':role==='prep'?'WAIT TICKET':'WAIT DRINK');setSelected(-1);},[role]);
  const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
  const change=(value:string)=>{if(!locked&&!observation)onChange(value);};
  const insert=()=>{if(locked||observation)return;const next=insertBlock(source,command,selected);setSelected(next.selected);change(next.source);};
  let depth=0;const rows=source.split('\n').map((raw,id)=>{const c=raw.trim();if(c==='END'||c==='ELSE')depth=Math.max(0,depth-1);const d=depth;if(isOpening(c)||c==='ELSE')depth++;return {id,raw,c,depth:Math.min(d,5)};}).filter(row=>row.c&&!row.c.startsWith('#'));
  return <><div className="editor-tabs"><button className={!textMode?'chosen':''} onClick={()=>onTextMode(false)}><Blocks size={14}/> Blocks</button><button className={textMode?'chosen':''} onClick={()=>onTextMode(true)} disabled={observation}><Code2 size={14}/> Text</button><span>{locked?<><LockKeyhole size={12}/> Playback locked</>:observation?'Observation':`${rows.length} / ${role==='query'?128:512} blocks`}</span></div>
  <div className="editor-body">
  {observation?<div className="auto-service"><div className="auto-icon">↻</div><strong>Automatic service</strong><p>Niko has this shift covered.</p><div>Take order <span>→</span> Prepare<br/>Serve <span>→</span> Clean</div><small>Watch the service, then help Query<br/>take over the counter.</small></div>:textMode?<textarea spellCheck={false} aria-label="Program source" value={source} onChange={e=>change(e.target.value)} readOnly={locked} className={`code-input ${failureLine>=0?'code-error':''}`}/>:<DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={({active,over})=>{if(over&&!locked){change(moveGroup(source,Number(active.id),Number(over.id)));setSelected(Number(over.id));}}}><SortableContext items={rows.map(r=>String(r.id))} strategy={verticalListSortingStrategy}><div className="block-list">{rows.map(row=><Row key={row.id} id={row.id} command={row.c} depth={row.depth} options={options} locked={locked} selected={selected===row.id} active={activeLine===row.id} failure={failureLine===row.id} onSelect={()=>setSelected(row.id)} onReplace={c=>{const lines=source.split('\n');lines[row.id]=c;change(lines.join('\n'));}} onMove={d=>{change(moveBlock(source,row.id,d));setSelected(Math.max(0,row.id+d));}} onDelete={()=>{change(deleteBlock(source,row.id));setSelected(-1);}}/>)}<button className="insert-hint" disabled={locked} onClick={()=>setSelected(-1)}>+ {rows.length?'Select a block to insert after it':'Choose your first instruction below'}</button></div></SortableContext></DndContext>}
  </div><div className="palette"><label htmlFor="instruction">INSTRUCTION LIBRARY <span>{selected>=0?`After block ${selected+1}`:'Add at the end'}</span></label><div><select id="instruction" value={command} onChange={e=>setCommand(e.target.value)} disabled={locked||observation}>{options.map(c=><option key={c} value={c}>{labels[c]??c}</option>)}</select><button className="add-button" aria-label="Add block" disabled={locked||observation} onClick={insert}><Plus size={17}/></button></div></div></>;
}
