/** Generate docs/campaign/ (the shift table and the shift pages) from the campaign sources. Run with `npm run docs:gen`. */
import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { extensionSeeds } from '../src/data/campaign/extension-seeds.ts';

const dir = new URL('../src/data/campaign/', import.meta.url);
const read = (path) => JSON.parse(readFileSync(new URL(path, dir), 'utf8'));

const manifest = read('manifest.json');
const actOne = manifest.order.map((id) => ({
  id,
  level: read(`levels/${id}.json`),
  lesson: read(`lessons/${id}.json`),
}));

// Extension mechanics come from extension-config.json: stages merge in order,
// so new shifts inherit the latest stage and docs never hardcode a seed count.
const mechanics = read('extension-config.json');
function tablesFor(level) {
  let tables;
  for (const { from, ...override } of mechanics.stages) {
    if (level < from) break;
    if (override.tables !== undefined) tables = override.tables;
  }
  if (tables === undefined) throw new Error(`no extension stage covers L${level}; extend extension-config.json`);
  return tables;
}

// Extension shifts derive from the structured seed table (no source-text parsing).
const seeds = extensionSeeds;
for (const seed of seeds) {
  for (const key of ['id', 'title', 'note', 'blocks', 'instructions']) {
    if (seed[key] === undefined) throw new Error(`extension seed missing ${key}: ${seed.id ?? '(unknown)'}`);
  }
}

const row = (id, title, tables, seedsCount, blocks, instructions, note) =>
  `| ${id} | ${title} | ${tables} | ${seedsCount} | ${blocks} | ${instructions} | ${note.split('.')[0]}. |`;

let md = `# Campaign shifts\n\nGenerated by \`npm run docs:gen\` from \`src/data/campaign/\`. Do not edit by hand.\n\nEach shift has a page with its story, lesson, customers and reference programs in [shifts/](shifts/README.md). Why each shift exists, what it builds on and where players slip is in the hand-kept [audit](AUDIT.md).\n\n`;
md += `| Shift | Title | Tables | Seeds | Block target | Step target | Note |\n| --- | --- | --- | --- | --- | --- | --- |\n`;
for (const { id, level, lesson } of actOne) {
  const title = level.title.replace(/^Level \d+: /, '');
  md +=
    row(id, title, level.active_tables, level.seeds.length, level.block_target, level.instruction_target, lesson.note) +
    '\n';
}
for (const seed of seeds) {
  md +=
    row(seed.id, seed.title, tablesFor(Number(seed.id.slice(1))), 3, seed.blocks, seed.instructions, seed.note) + '\n';
}

const outUrl = new URL('../docs/campaign/README.md', import.meta.url);
if (process.argv.includes('--check')) {
  let current = null;
  try {
    current = readFileSync(outUrl, 'utf8');
  } catch {
    console.error('docs:gen --check failed: docs/campaign/README.md is missing (run npm run docs:gen).');
    process.exit(1);
  }
  if (current !== md) {
    console.error('docs:gen --check failed: docs/campaign/README.md is stale (run npm run docs:gen).');
    process.exit(1);
  }
  console.log(`docs:gen check ok: ${actOne.length + seeds.length} shifts documented.`);
} else {
  mkdirSync(new URL('../docs/campaign/', import.meta.url), { recursive: true });
  writeFileSync(outUrl, md);
  console.log(`docs:gen ok: ${actOne.length + seeds.length} shifts documented.`);
  // The shift pages render from the built campaign (TypeScript), so the test that checks them also writes them.
  const pages = spawnSync('npx', ['vitest', 'run', 'tests/unit/data/shift-docs.test.ts'], {
    stdio: 'inherit',
    shell: process.platform === 'win32',
    env: { ...process.env, UPDATE_SHIFT_DOCS: '1' },
  });
  if (pages.status !== 0) process.exit(pages.status ?? 1);
}
