/** Generate docs/campaign/ from the campaign sources. Run with `npm run docs:gen`. */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../src/data/campaign/', import.meta.url);
const read = (path) => JSON.parse(readFileSync(new URL(path, dir), 'utf8'));

const manifest = read('manifest.json');
const actOne = manifest.order.map((id) => ({
  id,
  level: read(`levels/${id}.json`),
  lesson: read(`lessons/${id}.json`),
}));

// Extension seeds are machine-generated single-line records; parse them as data.
const seedsSrc = readFileSync(new URL('extension-seeds.ts', dir), 'utf8');
const seedLines = seedsSrc.split('\n').filter((line) => line.includes("{ id: 'L"));
if (seedLines.length !== 18) throw new Error(`expected 18 extension seeds, found ${seedLines.length}`);
const seeds = seedLines.map((line) => {
  const pick = (key) => {
    const m = line.match(new RegExp(`${key}: ('(?:[^'\\\\]|\\\\.)*'|"(?:[^"\\\\]|\\\\.)*"|\\d+)`));
    if (!m) throw new Error(`seed line missing ${key}: ${line.slice(0, 60)}`);
    return /^['"]/.test(m[1]) ? eval(m[1]) : Number(m[1]);
  };
  return { id: pick('id'), title: pick('title'), note: pick('note'), blocks: pick('blocks'), instructions: pick('instructions') };
});

const row = (id, title, tables, seedsCount, blocks, instructions, note) =>
  `| ${id} | ${title} | ${tables} | ${seedsCount} | ${blocks} | ${instructions} | ${note.split('.')[0]}. |`;

let md = `# Campaign shifts\n\nGenerated by \`npm run docs:gen\` from \`src/data/campaign/\`. Do not edit by hand.\n\n`;
md += `| Shift | Title | Tables | Seeds | Block target | Step target | Note |\n| --- | --- | --- | --- | --- | --- | --- |\n`;
for (const { id, level, lesson } of actOne) {
  const title = level.title.replace(/^Level \d+: /, '');
  md += row(id, title, level.active_tables, level.seeds.length, level.block_target, level.instruction_target, lesson.note) + '\n';
}
for (const seed of seeds) {
  const level = Number(seed.id.slice(1));
  const tables = level >= 31 ? 16 : level >= 29 ? 4 : level >= 24 ? 2 : 1;
  md += row(seed.id, seed.title, tables, 3, seed.blocks, seed.instructions, seed.note) + '\n';
}

mkdirSync(new URL('../docs/campaign/', import.meta.url), { recursive: true });
writeFileSync(new URL('../docs/campaign/README.md', import.meta.url), md);
console.log(`docs:gen ok: ${actOne.length + seeds.length} shifts documented.`);
